spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cd_shop?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      min-idle: 10
      max-active: 100
      initial-size: 20
#      监控页的配置
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123
#        重置按钮
        reset-enable: false
#        web监控功能
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      aop-patterns: com.atguigu.boot05webadmin.*
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
# Redis服务器地址，另外注意要开启Redis服务
  # Redis服务器连接端口
  # Redis服务器连接密码（默认为空）
  # 连接池最大连接数（使用负值表示没有限制）
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # 连接池中的最大空闲连接
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8